# Generated by Django 3.2.15 on 2022-09-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=18)),
                ('email', models.EmailField(max_length=50)),
                ('sex', models.CharField(max_length=10)),
            ],
        ),
    ]
